spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devflow
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: devflow
jwt:
  secret: "b8dfd29b2dd922fd494fb63a427e519dfaabc4489a4ade985c8eaaaef051a0f5272fd75ddda34211039997f8896b5f3693cd92eb75ea2bf786884aa0e31b9b36"
  access-expiry-ms: 900000
  refresh-expiry-days: 7
logging:
  level:
    root: INFO
    com.example.devflow: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlation-id}] %5p %c{1} 0%m%n"